site:
  title: Redis OM Spring Documentation
  url: https://redis.github.io/redis-om-spring
  start_page: redis-om-spring::index.adoc

content:
  sources:
    - url: ..
      branches: HEAD
      start_path: docs/content

runtime:
  fetch: true
  cache_dir: ./.cache/antora

ui:
  bundle:
    url: https://github.com/redis-developer/antora-ui-redis/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    toc: ~
    xrefstyle: short

antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true